import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'
import './globals.css'
import Header from "@/components/common/layout/header/Header";
import {Container} from "@mui/system";
import img from '../../public/background.jpg'


const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={roboto.className}>
            <div className='wrapper'>
                <Container sx={{mt: '5rem'}}>
                    <Header/>
                    <main className='main'>
                        {children}
                    </main>
                    {/*footer*/}
                </Container>
            </div>
        </body>
        </html>
    )
}
